[package]
name = "lzc-sdk-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.3"
prost-types = "0.13.3"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
walkdir = "2.5"
rayon = "1"
